package exception;

public enum ExceptionType {
    ATTRIBUTE_TYPE_ERROR,
    ATTRIBUTE_LENGTH_ERROR,
    NO_COlUMN_SELECTED_FOR_FILTER,
    NO_COLUMN_SELECTED_FOR_SORT,
    NO_COLUMN_SELECTED_FOR_REPORTS,
    COLUMN_NO_NUMERIC_FOR_AVERAGE,
    EMPTY_QUERY,
    NO_SELECTED_ROW
}
